### ISSUE TITLE
CocoaPods: Use of private header from outside its module

### ISSUE THREAD

**Issue by ciryon** [klarna/klarna-on-demand-ios#27]
Hi,

I'm integrating Klarna-on-Demand via CocoaPods but get the following when compiling:

path_to_project/Pods/Target Support Files/Klarna-on-Demand/Klarna-on-Demand-prefix.pch:11:13: Use of private header from outside its module: 'BDError.h'

(as well as several other similar errors)

My project uses Swift and has base iOS SDK level 8.1. In my Podfile I specify "use_frameworks!"

Any ideas what's wrong?

**Comment by grozen** [comment]
Heya ciryon,

Sorry to hear you are having problems. I remember that back when we did a few trial runs to see how smooth the integration is throwing, Swift into the mix proved... interesting.

It did work with sufficient coaxing, so I'm sure we can pass this hurdle as well.

The most efficient way for us to be able to help you (assuming you haven't sorted this out on your own already), is for you to trim your project down and send it over us. That way we can actually have something to work with, and you won't have to divulge any valuable intellectual property.

Is this something you would feel comfortable doing?

Thanks,
Guy

**Comment by tomerlevi444** [comment]
@ciryon The messages you describe are marked as warnings or errors?

**Comment by ciryon** [comment]
Hi, I'll see if I can package together a sample project that demonstrates the issue. I think it's reproducible from a standard Swift project and standard pod init and then add KlarnaOnDemand to Podfile.

The messages are errors.

**Comment by ciryon** [comment]
OK, I don't think a sample project is even necessary. It's very easy to reproduce:

1) Create a new project in XCode (Single View Application, Swift, iPhone)
2) pod init to generate a new Podfile and add pod 'Klarna-on-Demand' 
3) pod install and open the resulting xcworkspace file
4) Build

**Comment by grozen** [comment]
Hey @ciryon,

Sorry this is taking a while, but we **will** look into this.

Thanks,
Guy

**Comment by tomerlevi444** [comment]
Hey @ciryon,

I am using XCode Version 7.1.1 (7B1005) and performed that exact steps you mentioned, but the errors don't appear (actually, there are no warnings also).
Could you check if there's a specific configuration of your XCode application that causes the different behaviour?

**Comment by ciryon** [comment]
We've verified the problem on two separate machines. Please see this sample project which exposes the problems:

https://github.com/ciryon/KlarnaIssueProject

Just clone and open the workspace, then build.
(no need to run pod install as the Pods folder is included)

**Comment by KnowITiOSJohan** [comment]
What is the status on this issue? It would be nice if this would be fixed very soon.

**Comment by ciryon** [comment]
@KnowITiOSJohan *wave* :)

**Comment by KnowITiOSJohan** [comment]
I really want to push this issue forward. Here comes some new information that might help to you/us to get further with this issue.

First of all I could say that I got the Klarna-on-Demand SDK to work in this Swift project. That was when I used Objective-C only pods that was imported via CocoaPods. When I added another pod that was Swift only I added the `use_frameworks!` line in the Podfile when the problem started.

So if you are in a project where you could avoid using `use_frameworks!`, you are good to go.

The actual problem is within the pod spec file for the Klarna-on-Demand SDK. There are some lines like this

`crypto.private_header_files = '3rdParty/Crypto/**/*.h'`

That causes trouble. I made a local copy and changed a couple of lines of the pod spec and got it to work. However I still a get a couple of more warnings/errors that I did not manage to fix. I had to suppress warnings to get this to work.

@tomerlevi444 What are your conclusions about this problem?

**Comment by grozen** [comment]
Hey @KnowITiOSJohan, @ciryon,

Just wanted to chime in again and say that I definitely appreciate you taking the time and patience to help us solve the issue. I am sure @tomerlevi444 shares my sentiments, and we will put the latest info you gave us to good use.

**Comment by lilach** [comment]
@ciryon, thank you for reporting this bug, and @KnowITiOSJohan, thank you for your research.
This issue is fixed in v 1.1.1
Please let us know if you have any input on the subject
